#!/usr/bin/env python3
"""Render generated metered inference manifests from their sources.

Pass --check to fail when a committed file is stale instead of writing it.

gateway/apps/09-dashboards.yaml embeds dashboards/*.json; export an edited dashboard from Grafana
over the file, then run this script. App manifests are Helm templates, so every "{{" in a dashboard
(Grafana legend formats) is written as the JSON escape \\u007b\\u007b, which Grafana decodes and Helm
leaves alone. The rate card placeholders __INPUT_PRICE__ and __OUTPUT_PRICE__ become App parameters.

platform/apps/02-tenant-stack.yaml embeds tenant/apps/*.yaml and tenant/stacktemplate.yaml, and
platform/apps/03-cluster-template.yaml embeds source/virtualclustertemplate.yaml. Those sources are
templates themselves, so every "{{" and "}}" in them becomes a Helm string literal that renders back
to the same text. The template's __PLACEHOLDERS__ become values the App computes.
"""
import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent
sources = root / "dashboards"
target = root / "gateway" / "apps" / "09-dashboards.yaml"
tenant_stack_target = root / "platform" / "apps" / "02-tenant-stack.yaml"
cluster_template_target = root / "platform" / "apps" / "03-cluster-template.yaml"

HEADER = """\
# Step 9: the showback dashboards. GENERATED by community-stacks/metered-inference/render.py
# from community-stacks/metered-inference/dashboards/*.json. Edit the JSON sources, then re-run
# the script.
#
# metered-inference-showback   Every tenant cluster, for platform administrators. With
#                              platformIntegration it is also the Platform's Fleet Observability
#                              page.
# vcluster-cluster-observability
#                              One tenant cluster's usage. Only rendered with platformIntegration:
#                              the Platform's tenant cluster Observability tab embeds the dashboard
#                              with this UID, through a datasource scoped to that tenant cluster.
#
# The ConfigMaps land in Grafana's namespace, which step 8 moves to the Platform namespace when
# platformIntegration is on, and carry the label its dashboard sidecar watches.
apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: metered-inference-dashboards
  labels:
    inference.vcluster.com/stack: gateway
spec:
  displayName: '[Metered Inference Gateway - 9] Showback dashboards'
  description: Provisions the token showback dashboards into the Stack's Grafana.
  defaultNamespace: inference-observability
  config:
    manifests: |-
      {{- $platform := eq (toString .Values.platformIntegration) "true" }}
      {{- $ns := .Release.Namespace }}
      {{- if $platform }}{{ $ns = .Values.platformNamespace | default "vcluster-platform" }}{{ end }}
"""

CONFIGMAP = """\
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {name}
        namespace: {{{{ $ns }}}}
        labels:
          grafana_dashboard: metered-inference
      data:
        {file}: |-
{body}
"""

FOOTER = """\
  parameters:
    - variable: platformIntegration
      label: Serve through vCluster Platform
      description: Also provision the tenant cluster Observability tab dashboard, and follow Grafana into the Platform namespace.
      type: boolean
      defaultValue: "false"
    - variable: platformNamespace
      label: Platform namespace
      type: string
      defaultValue: vcluster-platform
    - variable: inputPricePerMillion
      label: Input price per million tokens
      description: Default rate card for prompt tokens, in US dollars. Viewers can change it on the dashboard.
      type: string
      defaultValue: "0.20"
      validation: '^[0-9]+(\\.[0-9]+)?$'
    - variable: outputPricePerMillion
      label: Output price per million tokens
      description: Default rate card for generated tokens, in US dollars. Viewers can change it on the dashboard.
      type: string
      defaultValue: "0.60"
      validation: '^[0-9]+(\\.[0-9]+)?$'
"""


def embed(path: Path) -> str:
    dashboard = json.loads(path.read_text())
    text = json.dumps(dashboard, indent=2)
    text = text.replace("{{", "\\u007b\\u007b").replace("}}", "\\u007d\\u007d")
    text = text.replace('"__INPUT_PRICE__"', '"{{ .Values.inputPricePerMillion | default "0.20" }}"')
    text = text.replace('"__OUTPUT_PRICE__"', '"{{ .Values.outputPricePerMillion | default "0.60" }}"')
    if "__INPUT_PRICE__" in text or "__OUTPUT_PRICE__" in text:
        raise SystemExit(f"{path}: a price placeholder is not a whole JSON string")
    return "\n".join(" " * 10 + line for line in text.splitlines())


def render() -> str:
    showback = CONFIGMAP.format(name="metered-inference-showback-dashboard", file="showback.json",
                                body=embed(sources / "showback.json"))
    tenant = CONFIGMAP.format(name="metered-inference-tenant-dashboard", file="tenant-usage.json",
                              body=embed(sources / "tenant-usage.json"))
    return (HEADER + showback + "      {{- if $platform }}\n      ---\n" + tenant
            + "      {{- end }}\n" + FOOTER)


TENANT_STACK_HEADER = """\
# Step 2: the tenant Stack. GENERATED by community-stacks/metered-inference/render.py from
# community-stacks/metered-inference/tenant/apps/*.yaml and
# community-stacks/metered-inference/tenant/stacktemplate.yaml. Edit those sources, then re-run the
# script.
#
# Registers, through the Platform's management API, the metered-inference-kubeai StackTemplate that
# the tenant cluster template runs in every tenant cluster, its Apps, and the
# metered-inference-endpoint App the template runs in each tenant cluster's namespace. Their own
# templates are escaped, so this App's Helm render leaves them exactly as they are in the sources.
apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: metered-inference-tenant-stack
  labels:
    inference.vcluster.com/stack: platform
spec:
  displayName: '[Metered Inference Platform - 2] Tenant Stack'
  description: Registers the metered-inference-kubeai StackTemplate and the Apps tenant clusters use.
  defaultNamespace: inference-gateway
  config:
    manifests: |-
"""

TENANT_STACK_FOOTER = """\
  parameters: []
"""

CLUSTER_TEMPLATE_HEADER = r"""# Step 3: the tenant cluster template. GENERATED by community-stacks/metered-inference/render.py
# from community-stacks/metered-inference/source/virtualclustertemplate.yaml. Edit that source,
# then re-run the script.
#
# Creates the metered-inference-kubevirt VirtualClusterTemplate with the endpoint settings fixed from
# the gateway Stack's contract, which the platform Stack's contract task reads, so tenants choose
# only the model, the API key, and the VMs. The cluster issuer and certificate verification follow
# from the TLS issuer: tenant clusters verify the endpoint's certificate only with Let's Encrypt
# production certificates, because they do not trust the self-signed or staging CAs.
apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: metered-inference-cluster-template
  labels:
    inference.vcluster.com/stack: platform
spec:
  displayName: '[Metered Inference Platform - 3] Tenant cluster template'
  description: Creates the Metered inference (KubeVirt) tenant cluster template, with the gateway Stack's endpoint settings filled in.
  defaultNamespace: inference-gateway
  config:
    manifests: |-
      {{- $domain := .Values.domain | default "" }}
      {{- if not (regexMatch "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)+$" $domain) }}
      {{- fail (printf "domain %q is not a DNS name. The platform Stack reads it from the gateway Stack's contract." $domain) }}
      {{- end }}
      {{- $tls := .Values.tlsIssuer | default "" }}
      {{- if not (has $tls (list "self-signed" "letsencrypt" "letsencrypt-staging" "none")) }}
      {{- fail (printf "tlsIssuer %q is not one the gateway Stack supports" $tls) }}
      {{- end }}
      {{- $scheme := .Values.scheme | default "" }}
      {{- if ne $scheme (ternary "http" "https" (eq $tls "none")) }}
      {{- fail (printf "scheme %q does not match tlsIssuer %q" $scheme $tls) }}
      {{- end }}
      {{- $clusterIssuer := ternary "" "metered-inference" (eq $tls "none") }}
      {{- $verifyTLS := ternary "true" "false" (eq $tls "letsencrypt") }}
      {{- $pullSecret := .Values.jobImagePullSecret | default "" }}
      {{- if not (regexMatch "^$|^[a-z0-9]([-a-z0-9.]*[a-z0-9])?$" $pullSecret) }}
      {{- fail (printf "jobImagePullSecret %q is not a Secret name" $pullSecret) }}
      {{- end }}
"""

CLUSTER_TEMPLATE_FOOTER = """\
  parameters:
    - variable: domain
      label: Inference domain
      description: The gateway Stack's endpoint domain, from its contract.
      type: string
      required: true
    - variable: scheme
      label: Endpoint scheme
      type: string
      options:
        - https
        - http
    - variable: tlsIssuer
      label: TLS issuer
      type: string
      options:
        - self-signed
        - letsencrypt
        - letsencrypt-staging
        - none
    - variable: jobImagePullSecret
      label: Job image pull Secret
      description: Passed to each tenant cluster's endpoint App.
      type: string
"""

PLACEHOLDERS = {
    "__DOMAIN__": "{{ $domain }}",
    "__SCHEME__": "{{ $scheme }}",
    "__CLUSTER_ISSUER__": "{{ $clusterIssuer }}",
    "__VERIFY_TLS__": "{{ $verifyTLS }}",
    "__JOB_IMAGE_PULL_SECRET__": "{{ $pullSecret }}",
}


def helm_escape(text: str) -> str:
    """Text that Helm renders back to itself: each {{ and }} becomes a string literal action."""
    return re.sub(r"\{\{|\}\}", lambda m: '{{ "{{" }}' if m.group() == "{{" else '{{ "}}" }}', text)


def without_header(path: Path) -> str:
    """The manifest without its leading comment block, which documents the source file."""
    lines = path.read_text().splitlines()
    while lines and (lines[0].startswith("#") or not lines[0].strip()):
        lines.pop(0)
    return "\n".join(lines)


def indent(text: str) -> str:
    return "\n".join((" " * 6 + line).rstrip() for line in text.splitlines())


def render_tenant_stack() -> str:
    paths = sorted((root / "tenant" / "apps").glob("*.yaml")) + [root / "tenant" / "stacktemplate.yaml"]
    docs = [helm_escape(without_header(path)) for path in paths]
    return TENANT_STACK_HEADER + indent("\n---\n".join(docs)) + "\n" + TENANT_STACK_FOOTER


def render_cluster_template() -> str:
    path = root / "source" / "virtualclustertemplate.yaml"
    text = helm_escape(without_header(path))
    for placeholder, value in PLACEHOLDERS.items():
        text = text.replace(placeholder, value)
    leftover = re.findall(r"__[A-Z_]+__", text)
    if leftover:
        raise SystemExit(f"{path}: unknown placeholders {sorted(set(leftover))}")
    return CLUSTER_TEMPLATE_HEADER + indent(text) + "\n" + CLUSTER_TEMPLATE_FOOTER


def main() -> int:
    targets = {
        target: render(),
        tenant_stack_target: render_tenant_stack(),
        cluster_template_target: render_cluster_template(),
    }
    status = 0
    for path, rendered in targets.items():
        name = path.relative_to(root.parents[1])
        if "--check" in sys.argv[1:]:
            if not path.exists() or path.read_text() != rendered:
                print(f"FAIL {name} is stale; run community-stacks/metered-inference/render.py", file=sys.stderr)
                status = 1
            else:
                print(f"ok {name} is up to date")
        else:
            path.write_text(rendered)
            print(f"wrote {name}")
    return status


if __name__ == "__main__":
    sys.exit(main())
